pipeline {
    agent any
    stages{
        stage('SCM') {
            steps {
            	git branch: "dev",
                url: "https://github.com/hsik0225/dropthecode.git"
            }
        }

        stage('Test with coverage') {
            steps {
                dir('backend') {
                    sh './gradlew testCoverage'
                }
            }
        }

        stage('SonarCloud PR analysis') {
            steps {
                withSonarQubeEnv('SonarCloud') {
                    dir('backend') {
                        sh "./gradlew --info sonarqube \
                        	-Dsonar.projectKey=hsik0225_dropthecode \
                        	-Dsonar.organization=seed \
                        	-Dsonar.pullrequest.provider=GitHub \
                        	-Dsonar.pullrequest.github.repository=hsik0225/dropthecoe \
                        	-Dsonar.pullrequest.key=${CHANGE_ID} \
                        	-Dsonar.pullrequest.base=dev \
                        	-Dsonar.pullrequest.branch=${BRANCH_NAME}"
                    }
                }
            }
        }
    }
}
